#!/bin/bash

# GCP Resource Inventory Script
# Lists all available resources in the current GCP project

echo "=========================================="
echo "GCP Resource Inventory - $(date)"
echo "Project: $(gcloud config get-value project)"
echo "=========================================="

echo ""
echo "1. PROJECT INFORMATION"
echo "-------------------"
echo "Current Project:"
gcloud config get-value project
echo ""
echo "Project Details:"
gcloud projects describe $(gcloud config get-value project) --format="table(name,projectId,createTime,lifecycleState)"

echo ""
echo "2. COMPUTE INSTANCES"
echo "-------------------"
echo "All Instances:"
gcloud compute instances list --format="table(name,zone,machineType,status,internalIp,externalIp)"

echo ""
echo "3. LOAD BALANCING RESOURCES"
echo "---------------------------"
echo "Forwarding Rules (Global):"
gcloud compute forwarding-rules list --global --format="table(name,IPAddress,IP_PROTOCOL,TARGET)"
echo ""
echo "Forwarding Rules (Regional):"
gcloud compute forwarding-rules list --format="table(name,region,IPAddress,IP_PROTOCOL,TARGET)"
echo ""
echo "Target Pools:"
gcloud compute target-pools list --format="table(name,region,sessionAffinity)"
echo ""
echo "Backend Services (Global):"
gcloud compute backend-services list --global --format="table(name,protocol,port,sessionAffinity)"
echo ""
echo "Backend Services (Regional):"
gcloud compute backend-services list --format="table(name,region,protocol,port,sessionAffinity)"
echo ""
echo "URL Maps:"
gcloud compute url-maps list --format="table(name,defaultService)"
echo ""
echo "Target HTTP Proxies:"
gcloud compute target-http-proxies list --format="table(name,urlMap)"
echo ""
echo "Target HTTPS Proxies:"
gcloud compute target-https-proxies list --format="table(name,urlMap)"

echo ""
echo "4. HEALTH CHECKS"
echo "-------------"
echo "HTTP Health Checks:"
gcloud compute http-health-checks list --format="table(name,host,port,requestPath)"
echo ""
echo "HTTPS Health Checks:"
gcloud compute https-health-checks list --format="table(name,host,port,requestPath)"
echo ""
echo "TCP Health Checks:"
gcloud compute health-checks list --filter="type:TCP" --format="table(name,port,protocol)"
echo ""
echo "SSL Health Checks:"
gcloud compute health-checks list --filter="type:SSL" --format="table(name,port,protocol)"
echo ""
echo "Health Checks (Global):"
gcloud compute health-checks list --global --format="table(name,type,protocol,port)"

echo ""
echo "5. INSTANCE GROUPS"
echo "----------------"
echo "Instance Groups (Managed):"
gcloud compute instance-groups list --format="table(name,zone,size,managedInstanceGroup)"
echo ""
echo "Instance Groups (Unmanaged):"
gcloud compute instance-groups unmanaged list --format="table(name,zone,size)"

echo ""
echo "6. NETWORKING RESOURCES"
echo "----------------------"
echo "VPC Networks:"
gcloud compute networks list --format="table(name,description,creationTimestamp)"
echo ""
echo "Subnetworks:"
gcloud compute subnets list --format="table(name,region,ipCidrRange,description)"
echo ""
echo "Firewall Rules:"
gcloud compute firewall-rules list --format="table(name,network,direction,priority,sourceRanges,allowed)"
echo ""
echo "Static IP Addresses (Global):"
gcloud compute addresses list --global --format="table(name,address,type,status)"
echo ""
echo "Static IP Addresses (Regional):"
gcloud compute addresses list --format="table(name,region,address,type,status)"

echo ""
echo "7. STORAGE RESOURCES"
echo "-------------------"
echo "Disks:"
gcloud compute disks list --format="table(name,zone,sizeGb,type,status)"
echo ""
echo "Snapshots:"
gcloud compute snapshots list --format="table(name,creationTimestamp,sizeGb,status)"
echo ""
echo "Images:"
gcloud compute images list --format="table(name,family,creationTimestamp,status)"

echo ""
echo "8. MACHINE TYPES & REGIONS"
echo "------------------------"
echo "Available Machine Types (first 20):"
gcloud compute machine-types list --limit=20 --format="table(name,zone,cpus,memoryMb)"
echo ""
echo "Available Regions:"
gcloud compute regions list --format="table(name,description,status)"
echo ""
echo "Available Zones:"
gcloud compute zones list --format="table(name,region,description,status)"

echo ""
echo "9. IAM & SERVICE ACCOUNTS"
echo "------------------------"
echo "Service Accounts:"
gcloud iam service-accounts list --format="table(email,displayName,creationTimestamp)"
echo ""
echo "Current Account:"
gcloud auth list --filter=status:ACTIVE --format="table(account,status)"

echo ""
echo "10. BILLING & QUOTAS"
echo "------------------"
echo "Billing Information:"
if gcloud beta billing accounts list --format="table(name,displayName,open)" 2>/dev/null; then
    echo "Billing accounts listed above"
else
    echo "No billing access or no billing accounts found"
fi
echo ""
echo "Quotas for current region:"
gcloud compute project-info describe --project=$(gcloud config get-value project) --format="flattened(quotas)" | head -20

echo ""
echo "=========================================="
echo "Resource Inventory Complete - $(date)"
echo "=========================================="
