# Custom Resource Definition Example
# Defines a new resource type (MyApp) in the Kubernetes API
# Allows creation of custom resources with specified schema

apiVersion: apiextensions.k8s.io/v1  # API version for CRD resources
kind: CustomResourceDefinition      # Resource type: CustomResourceDefinition

metadata:                        # Metadata about the CRD
  name: myapps.example.com       # Full name: plural.group (myapps.example.com)

spec:                           # CRD specification
  group: example.com            # API group for the custom resource
                               # Groups organize related resources

  versions:                     # Supported API versions
  - name: v1                    # Version name
    served: true                # Serve this version via API
    storage: true               # Store objects in this version
    schema:                     # OpenAPI v3 schema for validation
      openAPIV3Schema:          # Schema definition
        type: object            # Root object type
        properties:             # Object properties
          spec:                 # Spec field (standard Kubernetes pattern)
            type: object        # Object type for spec
            properties:         # Properties within spec
              replicas:         # Custom field for replica count
                type: integer   # Integer type validation

  scope: Namespaced             # Resource scope: Namespaced or Cluster
                               # Namespaced = exists within namespaces
                               # Cluster = global across cluster

  names:                       # Human-readable names for the resource
    plural: myapps             # Plural form (used in kubectl get myapps)
    singular: myapp            # Singular form
    kind: MyApp                # CamelCase kind (used in YAML/JSON)
