Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "generic/ubuntu2204"
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "192.168.50.10"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 6
    end
    vm1.vm.provision "shell", inline: <<-SHELL
      timedatectl set-timezone Europe/Paris
    SHELL
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "generic/ubuntu2204"
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.50.11"
    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 6
    end
    vm2.vm.provision "shell", inline: <<-SHELL
      timedatectl set-timezone Europe/Paris
    SHELL
  end
end

