# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configuration for host1
  config.vm.define "host1" do |host1|
    host1.vm.box = "ubuntu/jammy64"
    host1.vm.hostname = "host1"
    host1.vm.network "private_network", ip: "192.168.56.10"
    host1.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    
    host1.vm.provision "shell", inline: <<-SHELL
      timedatectl set-timezone Europe/Paris
    SHELL
    
    host1.vm.provider "virtualbox" do |vb|
      vb.name = "host1"
      vb.memory = "4096"
      vb.cpus = 4
    end
  end

  # Configuration for host2
  config.vm.define "host2" do |host2|
    host2.vm.box = "ubuntu/jammy64"
    host2.vm.hostname = "host2"
    host2.vm.network "private_network", ip: "192.168.56.11"
    host2.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    
    host2.vm.provision "shell", inline: <<-SHELL
      timedatectl set-timezone Europe/Paris
    SHELL
    
    host2.vm.provider "virtualbox" do |vb|
      vb.name = "host2"
      vb.memory = "4096"
      vb.cpus = 4
    end
  end

  # Configuration for host3
  config.vm.define "host3" do |host3|
    host3.vm.box = "ubuntu/jammy64"
    host3.vm.hostname = "host3"
    host3.vm.network "private_network", ip: "192.168.56.12"
    host3.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    
    host3.vm.provision "shell", inline: <<-SHELL
      timedatectl set-timezone Europe/Paris
    SHELL
    
    host3.vm.provider "virtualbox" do |vb|
      vb.name = "host3"
      vb.memory = "4096"
      vb.cpus = 4
    end
  end
end

